name: Build and deploy container
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://ecevacuationplanning.azurecr.io/
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ecevacuationplanning.azurecr.io/${{ vars.REGISTRY_USERNAME }}/evacuation-planning:${{ github.sha }}
          file: ./Dockerfile
